version: '3.5'
services:
  postgres:
    container_name: postgres_core
    image: postgres
    environment:
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpass"
      PGDATA: /data/postgres
    volumes:
       - ./docker_data/postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - nlxi_core
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pguser@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpass"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      # sudo chown -R 5050:5050 <host_directory>
       - ./docker_data/pgadmin:/var/lib/pgadmin

    ports:
      - "8091:80"
    networks:
      - nlxi_core
    restart: unless-stopped

networks:
  nlxi_core:
    driver: bridge
